# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'MapRemark' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MapRemark
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'

  target 'MapRemarkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MapRemarkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
